# Generated by Django 3.1.2 on 2020-10-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentScoreModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(max_length=30)),
                ('level', models.CharField(max_length=30)),
                ('newspubName', models.CharField(max_length=30)),
                ('score', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('rank', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
